variables:
  GIT_SUBMODULE_STRATEGY: recursive

.docker_before_script_anchor: &docker_before_script_anchor
  before_script:
    - apt update -y && apt install python3-pip -y
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt

.singularity_before_script_anchor: &singularity_before_script_anchor
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - export BASETEMP=$RUN_BASE_DIR/$CI_COMMIT_REF_NAME/$CI_JOB_ID
    - echo $BASETEMP
    - mkdir -p $BASETEMP

stages:
  - sanity
  - dry-run
  - integration

test_sanities:
  <<: *docker_before_script_anchor
  script:
    - pytest-3 --tag sanity
  image: lumc/singularity-snakemake:3.5.2-5.9.1
  tags:
    - docker
  stage: sanity

test_dry_run:
  <<: *docker_before_script_anchor
  script:
    - pytest-3 --tag dry-run
  image: lumc/singularity-snakemake:3.5.2-5.9.1
  tags:
    - docker
  stage: dry-run


test_integration:
  <<: *singularity_before_script_anchor
  script:
    - pytest-3 --tag integration --basetemp ${BASETEMP} --keep-workflow-wd
  tags:
    - slurm
  stage: integration
