variables:
  GIT_SUBMODULE_STRATEGY: recursive

.docker_before_script_anchor: &docker_before_script_anchor
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

stages:
  - sanity
  - dry-run
  - integration
  - functional

test_sanities:
  <<: *docker_before_script_anchor
  script:
    - py.test --tag sanity
  image: python:3.6-stretch
  tags:
    - docker
  stage: sanity

test_dry_run:
  <<: *docker_before_script_anchor
  script:
    - py.test --tag dry-run
  image: python:3.6-stretch
  tags:
    - docker
  stage: dry-run


test_integration_singularity:
  before_script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install -r requirements-dev.txt
  script:
    - py.test --tag singularity-integration
  image: lumc/singularity-snakemake:3.0.3-5.4.0
  tags:
    - docker
  stage: integration

test_integration:
  before_script:
    - export BASETEMP=$(mktemp -p ${RUN_BASE_DIR} -d)
  script:
    - source ${CONDA_SH}
    - conda activate hutspot-pipeline
    - export PATH=${PATH}:${CONDA_EXTRA_PATH}
    - py.test --tag integration --basetemp ${BASETEMP} --keep-workflow-wd
  tags:
    - slurm
  stage: integration

test_functional:
  before_script:
    - export BASETEMP=$(mktemp -p ${RUN_BASE_DIR} -d)
  script:
    - source ${CONDA_SH}
    - conda activate hutspot-pipeline
    - export PATH=${PATH}:${CONDA_EXTRA_PATH}
    - py.test --tag functional --basetemp ${BASETEMP} --keep-workflow-wd
  tags:
    - slurm
  stage: functional
  only:
    - schedules