image: python:3.6-stretch

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

test_sanities:
  script:
    - py.test --tag sanity
  tags:
    - docker

test_dry_run:
  script:
    - py.test --tag dry-run
  tags:
    - docker
