variables:
  GIT_SUBMODULE_STRATEGY: recursive

.docker_before_script_anchor: &docker_before_script_anchor
  before_script:
    - apt update -y && apt install python3-pip -y
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt

stages:
  - sanity
  - dry-run
  - integration
  - functional

test_sanities:
  <<: *docker_before_script_anchor
  script:
    - pytest-3 --tag sanity
  image: lumc/singularity-snakemake:3.5.2-5.9.1
  tags:
    - docker
  stage: sanity

test_dry_run:
  <<: *docker_before_script_anchor
  script:
    - pytest-3 --tag dry-run
  image: lumc/singularity-snakemake:3.5.2-5.9.1
  tags:
    - docker
  stage: dry-run


test_integration:
  before_script:
    - export BASETEMP=$(mktemp -p ${RUN_BASE_DIR} -d)
  script:
    - pytest-3 --tag integration --basetemp ${BASETEMP} --keep-workflow-wd
  image: lumc/singularity-snakemake:3.5.2-5.9.1
  tags:
    - slurm
  stage: integration

test_functional:
  before_script:
    - export BASETEMP=$(mktemp -p ${RUN_BASE_DIR} -d)
  script:
    - pytest-3 --tag functional --basetemp ${BASETEMP} --keep-workflow-wd
  tags:
    - slurm
  stage: functional
  only:
    - schedules

