name: hutspot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aioeasywebdav=2.2.0
  - aiohttp=3.5.4
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - async-timeout=3.0.1
  - attrs=19.1.0
  - bcrypt=3.1.4
  - boto3=1.9.138
  - botocore=1.12.138
  - ca-certificates=2019.3.9
  - cachetools=2.1.0
  - cairo=1.16.0
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - configargparse=0.13.0
  - cryptography=2.6.1
  - datrie=0.7.1
  - decorator=4.4.0
  - docutils=0.14
  - dropbox=9.2.0
  - expat=2.2.5
  - filechunkio=1.8
  - fontconfig=2.13.1
  - freetype=2.10.0
  - ftputil=3.4
  - gettext=0.19.8.1
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - glib=2.58.3
  - google-api-core=1.10.0
  - google-auth=1.6.3
  - google-cloud-core=0.29.1
  - google-cloud-storage=1.15.0
  - google-resumable-media=0.3.2
  - googleapis-common-protos=1.5.9
  - graphite2=1.3.13
  - graphviz=2.38.0
  - harfbuzz=2.4.0
  - icu=58.2
  - idna=2.8
  - idna_ssl=1.1.0
  - jinja2=2.10.1
  - jmespath=0.9.4
  - jpeg=9c
  - jsonschema=3.0.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.7.1
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - multidict=4.5.2
  - ncurses=6.1
  - networkx=2.3
  - numpy=1.16.3
  - openblas=0.3.5
  - openssl=1.1.1b
  - pandas=0.24.2
  - pango=1.40.14
  - paramiko=2.4.2
  - pcre=8.41
  - pip=19.1
  - pixman=0.34.0
  - prettytable=0.7.2
  - protobuf=3.7.1
  - psutil=5.6.2
  - pthread-stubs=0.4
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.4
  - pycparser=2.19
  - pyfaidx=0.5.0
  - pygraphviz=1.5
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyrsistent=0.15.1
  - pysftp=0.2.9
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.8.0
  - python-irodsclient=0.7.0
  - pytz=2019.1
  - pyyaml=5.1
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.21.0
  - rsa=3.4.2
  - s3transfer=0.2.0
  - setuptools=41.0.1
  - six=1.12.0
  - smmap2=2.0.5
  - snakemake=5.4.5
  - snakemake-minimal=5.4.5
  - sqlite=3.26.0
  - tk=8.6.9
  - typing_extensions=3.7.2
  - urllib3=1.24.2
  - wheel=0.33.1
  - wrapt=1.11.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zlib=1.2.11
