name: hutspot
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- cyvcf2=0.8.0=py36_0
- pyvcf=0.6.8=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- click=6.7=py36_0
- coloredlogs=7.1=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- expat=2.2.1=0
- fontconfig=2.12.1=5
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.53.5=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- humanfriendly=4.4=py36_0
- icu=58.1=1
- jpeg=9b=2
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=1
- libxcb=1.12=1
- libxml2=2.9.5=0
- matplotlib=2.1.0=py36_1
- ncurses=5.9=10
- openssl=1.0.2l=0
- pandas=0.21.0=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=0
- pip=9.0.1=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.3=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_1
- qt=5.6.2=3
- readline=6.2=0
- seaborn=0.8.1=py36_0
- setuptools=36.6.0=py36_1
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- statsmodels=0.8.0=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- wheel=0.30.0=py_1
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zlib=1.2.8=3
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- scipy=0.19.1=np113py36_0
- pip:
  - backports.functools-lru-cache==1.4

